### ISSUE TITLE
Example Async SFTP sensor DAG fails on KubernetesExecutor deployment

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#1057]
The example Async SFTP sensor DAG has been failing on KubernetesExecutor deployment since the deployment creation. We need to debug and fix the issue.
```
[2023-05-08, 02:06:40 UTC] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/example_sftp.py", line 189, in ssh_and_run_command
    client.connect(hostname=instance_public_dns_name, username=kwargs["username"], pkey=key)
  File "/usr/local/lib/python3.10/site-packages/paramiko/client.py", line 459, in connect
    self._auth(
  File "/usr/local/lib/python3.10/site-packages/paramiko/client.py", line 790, in _auth
    raise saved_exception
  File "/usr/local/lib/python3.10/site-packages/paramiko/client.py", line 690, in _auth
    self._transport.auth_publickey(username, pkey)
  File "/usr/local/lib/python3.10/site-packages/paramiko/transport.py", line 1640, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/usr/local/lib/python3.10/site-packages/paramiko/auth_handler.py", line 259, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
```

**Comment by Lee-W** [comment]
@pankajkoti Is this something related to permission setup on the new environment?

**Comment by pankajkoti** [comment]
@Lee-W I could not diagnose what could be wrong exactly. I started debugging this but could not take it ahead. I have pushed commit here to print some debug logs https://github.com/astronomer/astronomer-providers/tree/debug-sftp-on-ke 

You might want to deploy the branch on KE and check what could be going wrong. Essentially there is some `paramiko` connection issue that is happening on KE but not CE. But, did not get good chance to debug further.

**Comment by Lee-W** [comment]
Thanks! Let me check how I can fix it

**Comment by Lee-W** [comment]
It might relate to something other than the security group setup I mentioned in today's meeting. One other finding is that we're able to connect to the ec2 instance created by the CE deployment from the KE deployment but still can't connect to the one created by KE deployment itself

**Comment by Lee-W** [comment]
I just found out the root cause of this failure. It's due to the wrong user name used. The next step is to find out why CE, KE deployment creates ec2 instance on different platform.

**Comment by Lee-W** [comment]
It relates to the `AMI_ID` we set up in the airflow instance.

**Comment by pankajkoti** [comment]
hi @Lee-W , I just checked that you're an admin in the workspace. So you should be able to set values to deployment variable `AMI_ID` if you know what value to set or would like to try and debug.
